name: Binary releases

on:
  push:
    tags: [ 0.*, 1.*, test-* ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - run: git fetch --tags

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: "[ -f .ci-skip-tests ] && echo 'Skipping tests' || dotnet test --no-build --verbosity normal"

    - name: Pack
      run: |
        dotnet publish -r win-x64 -p:AssemblyName=MBW.Tools.ZwaveJs2Mqtt.win -o Build --self-contained -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:GenerateDocumentationFile=False
        dotnet publish -r linux-x64 -p:AssemblyName=MBW.Tools.ZwaveJs2Mqtt.linux -o Build --self-contained -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:GenerateDocumentationFile=False
        dotnet publish -r osx-x64 -p:AssemblyName=MBW.Tools.ZwaveJs2Mqtt.osx -o Build --self-contained -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:GenerateDocumentationFile=False
    
    - name: Promote to release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: |
          Build/**
