name: Binary releases

on:
  push:
    tags: [ 0.*, 1.*, test-* ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - run: git fetch --tags

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: "[ -f .ci-skip-tests ] && echo 'Skipping tests' || dotnet test --no-build --verbosity normal"

    - name: Pack
      if: github.ref == 'refs/heads/master'
      run: |
        dotnet publish -o Build/win-x64 -r win-x64 --self-contained -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true
        dotnet publish -o Build/linux-x64 -r linux-x64 --self-contained -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true
        dotnet publish -o Build/osx-x64 -r osx-x64 --self-contained -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true
    
    - name: Promote to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Build/**
